#!/bin/sh

 wall=$(find ~/my-walls/ -type f -name "*.jpg" -o -name "*.png" | shuf -n 1 )
#wall=~/my-walls/black.png
xwallpaper --zoom $wall

#generate color scheme

wal -c
wal -i $wall

xdotool key super+F5
